name: Build LIEF (Android AArch64) - Professional DEB

on:
  workflow_dispatch:
    inputs:
      ndk_version:
        description: "Android NDK Version"
        default: 'r27c'
        required: true

permissions:
  contents: write

jobs:
  build-lief:
    name: Build LIEF for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake build-essential dpkg-dev

      - name: Setup NDK
        run: |
          # 仿照 OLLVM 脚本下载 NDK
          curl -sSfL -o android-ndk.zip "https://dl.google.com/android/repository/android-ndk-${{ inputs.ndk_version }}-linux.zip"
          unzip -qq android-ndk.zip
          # 获取 NDK 的绝对路径并写入环境变量
          NDK_PATH=$(pwd)/android-ndk-${{ inputs.ndk_version }}
          echo "NDK_ROOT=$NDK_PATH" >> $GITHUB_ENV

       - name: Configure CMake
        run: |
          mkdir -p build
          cmake -G Ninja -B build \
            -DCMAKE_TOOLCHAIN_FILE=${{ env.NDK_ROOT }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-28 \
            -DANDROID_STL=c++_static \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIEF_INSTALL=ON \
            -DLIEF_EXAMPLES=OFF \
            -DLIEF_TESTS=OFF \
            -DCPACK_GENERATOR=DEB \
            -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=aarch64 \
            -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr \
            -DCPACK_SET_DESTDIR=OFF \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/data/data/com.termux/files/usr


      - name: Build & Package
        run: |
          cmake --build build -j$(nproc)
          cd build && cpack -G DEB

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: lief-v${{ github.run_number }}
          name: LIEF Android AArch64 (NDK ${{ inputs.ndk_version }})
          body: |
            LIEF build for Android (AArch64).
            
            **Details:**
            - **NDK Version:** `${{ inputs.ndk_version }}`
            - **Prefix:** `/data/data/com.termux/files/usr` (Termux Compatible)
            - **STL:** `c++_static`
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

